Removed a lot of i3 customization packages and added Alacritty back to setup along with its config

diff --git a/setup/fedora b/setup/fedora
--- a/setup/fedora
+++ b/setup/fedora
@@ -1,6 +1,8 @@
 #!/bin/bash
 set -e 
 
+SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
+
 # ========================================
 # Miscellaneous
 # ========================================
@@ -12,10 +14,6 @@ fi
 if ! [ -f "$HOME/Pictures/wallpaper/nature.jpg" ]; then
     curl -L --create-dirs https://images.hdqwalls.com/download/tranquility-minimal-4k-6q-2560x1440.jpg > $HOME/Pictures/wallpaper/nature.jpg
 fi
-
-# ========================================
-# Tools and Applications Installation
-# ========================================
 
 # Install Neofetch
 if ! [ -x "$(command -v neofetch)" ]; then
@@ -48,9 +46,7 @@ if ! [ -x "$(command -v nvim)" ]; then
 fi
 
 # Copy Nvim configuration to .config/
-if ! [ -d "./nvim" ]; then 
-    cp -r ../nvim $HOME/.config
-fi
+cp -r $SCRIPT_DIR/../nvim $HOME/.config
 
 # Install Packer.nvim
 if ! [ -d "$HOME/.local/share/nvim/site/pack/packer/start/packer.nvim" ]; then
@@ -69,95 +65,56 @@ if ! [ -x "$(command -v i3)" ]; then
     sudo dnf install -y i3
 fi
 
-# Create i3 config
-if ! [ -d "$HOME/.config/i3" ]; then
-    cp -r ../i3 $HOME/.config
-fi
+# # Copy i3 configuration to .config/
+# cp -r $SCRIPT_DIR/../nvim $HOME/.config
 
 # Install Feh
 if ! [ -x "$(command -v feh)" ]; then
     sudo dnf install -y feh
 fi
 
-# Create fonts config
-if ! [ -d "$HOME/.local/share/fonts" ]; then
-    cp -r ../fonts $HOME/.local/share
-fi
-
-# Install Rofi
-if ! [ -x "$(command -v rofi)" ]; then
-    sudo dnf install -y rofi
-fi
-
-# Create Rofi config
-if ! [ -d "$HOME/.config/rofi" ]; then
-    cp -r ../rofi $HOME/.config
-fi
-
-# Install Picom
-if ! [ -x "$(command -v picom)" ]; then
-    sudo dnf install -y picom
-fi
-
-# Create Picom config
-if ! [ -d "$HOME/.config/picom" ]; then
-    cp -r ../picom $HOME/.config
-fi
-
-# Install PolyBar
-if ! [ -x "$(command -v polybar)" ]; then
-    sudo dnf install -y polybar
-fi
-
-# Install pip3; needed for pywal
-if ! [ -x "$(command -v pip3)" ]; then
-    sudo dnf install -y python3-pip
-fi
-
-# Install pywal; needed for PolyBar themes
-if ! [ -x "$(command -v wal)" ]; then
-    git clone https://github.com/dylanaraps/pywal
-    cd pywal
-    pip3 install --user .
-    cd ..
-    rm -rf pywal
-fi
-
-# Install calc; needed for PolyBar themes
-if ! [ -x "$(command -v calc)" ]; then
-    sudo dnf install -y calc
-fi
-
-# Install networkmanager_dmenu; needed for PolyBar themes
-if ! [ -x "$(command -v networkmanager_dmenu)" ]; then
-    git clone https://github.com/firecat53/networkmanager-dmenu.git
-    cd networkmanager-dmenu
-    cp networkmanager_dmenu $HOME/.local/bin
-    cd ..
-    rm -rf networkmanager-dmenu
-fi
-
-# Create PolyBar config
-if ! [ -d "$HOME/.config/polybar" ]; then
-    cp -r ../polybar $HOME/.config
-fi
-
-# # ========================================
-# # Alacritty Installation
-# # ========================================
-# 
-# if ! [ -x "$(command -v alacritty)" ]; then
-#     git clone https://github.com/alacritty/alacritty.git
-#     cd alacritty
-#     sudo dnf install -y cmake freetype-devel fontconfig-devel libxcb-devel libxkbcommon-devel g++
-#     cargo build --release
-#     sudo cp target/release/alacritty /usr/local/bin # or anywhere else in $PATH
-#     sudo cp extra/logo/alacritty-term.svg /usr/share/pixmaps/Alacritty.svg
-#     sudo desktop-file-install extra/linux/Alacritty.desktop
-#     sudo update-desktop-database
-#     mkdir -p ~/.bash_completion
-#     cp extra/completions/alacritty.bash ~/.bash_completion/alacritty
-#     echo "source ~/.bash_completion/alacritty" >> ~/.bashrc
-#     cd ..
-#     rm -rf alacritty
+# # Picom
+# if ! [ -x "$(command -v picom)" ]; then
+#     sudo dnf install -y picom
 # fi
+
+# ========================================
+# Alacritty Installation
+# ========================================
+
+# Install Alacirtty
+if ! [ -x "$(command -v alacritty)" ]; then
+    # Clone directory
+    git clone https://github.com/alacritty/alacritty.git
+
+    # Build binary
+    cd alacritty
+    sudo dnf install -y cmake freetype-devel fontconfig-devel libxcb-devel libxkbcommon-devel g++
+    cargo build --release
+
+    # Save binary into $PATH
+    sudo cp target/release/alacritty /usr/local/bin # or anywhere else in $PATH
+
+    # Create desktop shortcut for binary
+    sudo cp extra/logo/alacritty-term.svg /usr/share/pixmaps/Alacritty.svg
+    sudo desktop-file-install extra/linux/Alacritty.desktop
+    sudo update-desktop-database
+
+    # Include autocompletion
+    mkdir -p ~/.bash_completion
+    cp extra/completions/alacritty.bash ~/.bash_completion/alacritty
+    echo "source ~/.bash_completion/alacritty" >> ~/.bashrc
+
+    # Clean up
+    cd ..
+    rm -rf alacritty
+fi
+
+# Install fonts
+NUM_OF_JETBRAINS_FONT=$(fc-list | grep 'ttf: JetBrains Mono' | wc -l)
+if [ "$NUM_OF_JETBRAINS_FONT" = "0" ]; then
+    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/JetBrains/JetBrainsMono/master/install_manual.sh)"
+fi
+
+# Copy Alacritty configuration to .config/
+cp -r $SCRIPT_DIR/../alacritty $HOME/.config
